// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview Explains why a piece of content might be misleading.
 *
 * - explainMisleadingIndicators - A function that handles the explanation process.
 * - ExplainMisleadingIndicatorsInput - The input type for the explainMisleadingIndicators function.
 * - ExplainMisleadingIndicatorsOutput - The return type for the explainMisleadingIndicators function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ExplainMisleadingIndicatorsInputSchema = z.object({
  content: z.string().describe('The content to be analyzed for misleading indicators.'),
});
export type ExplainMisleadingIndicatorsInput = z.infer<typeof ExplainMisleadingIndicatorsInputSchema>;

const ExplainMisleadingIndicatorsOutputSchema = z.object({
  explanation: z.string().describe('Explanation of why the content might be misleading.'),
});
export type ExplainMisleadingIndicatorsOutput = z.infer<typeof ExplainMisleadingIndicatorsOutputSchema>;

export async function explainMisleadingIndicators(input: ExplainMisleadingIndicatorsInput): Promise<ExplainMisleadingIndicatorsOutput> {
  return explainMisleadingIndicatorsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'explainMisleadingIndicatorsPrompt',
  input: {schema: ExplainMisleadingIndicatorsInputSchema},
  output: {schema: ExplainMisleadingIndicatorsOutputSchema},
  prompt: `Analyze the following content and explain why it might be misleading. Consider factors such as emotional language, lack of credible sources, inconsistencies with known facts, and potential biases.\n\nContent: {{{content}}}`,
});

const explainMisleadingIndicatorsFlow = ai.defineFlow(
  {
    name: 'explainMisleadingIndicatorsFlow',
    inputSchema: ExplainMisleadingIndicatorsInputSchema,
    outputSchema: ExplainMisleadingIndicatorsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
