version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - REQUEST_SIZE_LIMIT=50mb
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - ./backend/src:/app/backend/src
      - ./backend/dist:/app/backend/dist
    networks:
      - unmai-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://localhost:3001
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    depends_on:
      - backend
    networks:
      - unmai-network

networks:
  unmai-network:
    driver: bridge

# For development, you can also add volumes for hot reloading:
# volumes:
#   - ./frontend/src:/app/frontend/src
#   - ./frontend/pages:/app/frontend/pages
