
'use client';

import { createContext, useState, useContext, ReactNode, useCallback } from 'react';

type TranslationReplacements = Record<string, string | number>;

type LanguageContextType = {
  language: string;
  setLanguage: (language: string) => void;
  translate: (key: string, replacements?: TranslationReplacements) => string;
};

const DEFAULT_LANGUAGE = 'en-US';

const TRANSLATIONS: Record<string, Record<string, string>> = {
  'en-US': {
    'input.placeholder.default': 'Analyze text, URL, or paste/drop an image, video, or audio file...',
    'input.placeholder.recording': 'Recording audio...',
    'input.placeholder.listening': 'Listening...',
    'input.placeholder.file': 'Add your question or analysis request',
    'input.placeholder.ready': 'Ready to analyze your content',
    'input.dropHere': 'Drop your file here',
    'input.attachFile': 'Attach file',
    'input.startVoice': 'Start Voice Input',
    'input.stopRecording': 'Stop Recording',
    'input.stopRecognition': 'Stop Recognition',
    'card.heading.description': 'Description',
    'card.placeholder.noDescription': 'No description available',
    'card.heading.summary': 'Information Summary',
    'card.placeholder.noSummary': 'No summary available',
    'card.heading.educational': 'Educational Insight: Manipulation Techniques & Protection Measures',
    'card.heading.sources': 'Sources, Trust Scores & Verdict',
    'card.heading.educationalSection': 'Educational Insights',
    'card.heading.misleadingIndicators': 'Misleading Indicators:',
    'card.heading.deepfakeDetection': 'Deepfake Detection:',
    'card.badge.detected': 'Detected',
    'card.badge.notDetected': 'Not Detected',
    'card.text.confidencePercent': '{{value}}% confidence',
    'card.label.overallVerdict': 'Overall Verdict:',
    'card.trust.sourceIntegrity': 'Source Integrity',
    'card.trust.contentAuthenticity': 'Content Authenticity',
    'card.trust.trustExplainability': 'Trust Explainability',
    'card.heading.sourceInformation': 'Source Information',
    'card.label.domain': 'Domain:',
    'card.label.author': 'Author:',
    'card.label.published': 'Published:',
    'card.label.reputation': 'Reputation:',
    'card.label.status': 'Status:',
    'card.label.ssl': 'SSL:',
    'card.text.sslEnabled': 'Enabled',
    'card.text.sslDisabled': 'Disabled',
    'card.heading.sourcesButton': 'Sources',
    'card.dialog.title': 'Sources & Verification Details',
    'card.dialog.description': 'Source information and verification results',
    'card.dialog.referenced': 'Referenced Sources ({{count}})',
    'card.dialog.noSources': 'No sources available for this analysis',
    'card.text.hostnameProtocol': '{{protocol}}',
    'card.heading.misleadingIndicatorsInline': 'Misleading Indicators:',
    'card.text.misleadingConfidence': '{{value}}%',
    'card.text.deepfakeConfidence': 'Confidence:',
    'card.details.technical': 'Technical details',
    'card.dialog.sourcesFallback': 'Source {{index}}',
    'card.text.noSourcesButton': 'No sources',
    'card.badge.confidenceLabel': 'Confidence: {{value}}%',
    'card.dialog.sourceMetadataSection': 'Source Information',
    'card.dialog.noSourceUrl': 'No URL provided',
    'card.label.credibility': 'Cred {{value}}%',
    'card.banner.deepfakeDetected': 'Deepfake Detected',
    'card.banner.deepfakeNotDetected': 'No Deepfake Detected',
    'card.heading.misleadingSection': 'Misleading Indicators',
    'card.button.close': 'Close',
    'dynamic.error.analysisFailed': 'Analysis could not be completed.'
  },
  'hi-IN': {
    'input.placeholder.default': 'पाठ, URL का विश्लेषण करें या कोई छवि, वीडियो, या ऑडियो फ़ाइल पेस्ट/ड्रॉप करें...',
    'input.placeholder.recording': 'ऑडियो रिकॉर्ड हो रहा है...',
    'input.placeholder.listening': 'सुन रहा है...',
    'input.placeholder.file': 'अपना प्रश्न या विश्लेषण अनुरोध जोड़ें',
    'input.placeholder.ready': 'आपकी सामग्री का विश्लेषण करने के लिए तैयार',
    'input.dropHere': 'अपनी फ़ाइल यहाँ छोड़ें',
    'input.attachFile': 'फ़ाइल संलग्न करें',
    'input.startVoice': 'वॉइस इनपुट प्रारंभ करें',
    'input.stopRecording': 'रिकॉर्डिंग रोकें',
    'input.stopRecognition': 'सुनना रोकें',
    'card.heading.description': 'वर्णन',
    'card.placeholder.noDescription': 'कोई वर्णन उपलब्ध नहीं',
    'card.heading.summary': 'सूचना सारांश',
    'card.placeholder.noSummary': 'कोई सारांश उपलब्ध नहीं',
    'card.heading.educational': 'शैक्षिक अंतर्दृष्टि: हेरफेर तकनीकें और सुरक्षा उपाय',
    'card.heading.sources': 'स्रोत, विश्वसनीयता स्कोर और निर्णय',
    'card.heading.educationalSection': 'शैक्षिक अंतर्दृष्टियाँ',
    'card.heading.misleadingIndicators': 'भ्रामक संकेतक:',
    'card.heading.deepfakeDetection': 'डीपफेक जाँच:',
    'card.badge.detected': 'पाया गया',
    'card.badge.notDetected': 'नहीं पाया गया',
    'card.text.confidencePercent': '{{value}}% भरोसा',
    'card.label.overallVerdict': 'अंतिम निर्णय:',
    'card.trust.sourceIntegrity': 'स्रोत अखंडता',
    'card.trust.contentAuthenticity': 'सामग्री प्रामाणिकता',
    'card.trust.trustExplainability': 'विश्वास स्पष्टता',
    'card.heading.sourceInformation': 'स्रोत जानकारी',
    'card.label.domain': 'डोमेन:',
    'card.label.author': 'लेखक:',
    'card.label.published': 'प्रकाशित:',
    'card.label.reputation': 'प्रतिष्ठा:',
    'card.label.status': 'स्थिति:',
    'card.label.ssl': 'SSL:',
    'card.text.sslEnabled': 'सक्रिय',
    'card.text.sslDisabled': 'निष्क्रिय',
    'card.heading.sourcesButton': 'स्रोत',
    'card.dialog.title': 'स्रोत और सत्यापन विवरण',
    'card.dialog.description': 'स्रोत जानकारी और सत्यापन परिणाम',
    'card.dialog.referenced': 'संदर्भित स्रोत ({{count}})',
    'card.dialog.noSources': 'इस विश्लेषण के लिए कोई स्रोत उपलब्ध नहीं',
    'card.text.deepfakeConfidence': 'भरोसा:',
    'card.details.technical': 'तकनीकी विवरण',
    'card.banner.deepfakeDetected': 'डीपफेक पाया गया',
    'card.banner.deepfakeNotDetected': 'डीपफेक नहीं पाया गया',
    'dynamic.error.analysisFailed': 'विश्लेषण पूरा नहीं हो सका।'
  },
  'bn-IN': {
    'input.placeholder.default': 'টেক্সট, URL বিশ্লেষণ করুন অথবা ছবি, ভিডিও বা অডিও ফাইল পেস্ট/ড্রপ করুন...',
    'input.placeholder.recording': 'অডিও রেকর্ড হচ্ছে...',
    'input.placeholder.listening': 'শুনছে...',
    'input.placeholder.file': 'আপনার প্রশ্ন বা বিশ্লেষণ অনুরোধ যোগ করুন',
    'input.placeholder.ready': 'আপনার বিষয়বস্তু বিশ্লেষণের জন্য প্রস্তুত',
    'input.dropHere': 'আপনার ফাইল এখানে ফেলুন',
    'input.attachFile': 'ফাইল সংযুক্ত করুন',
    'input.startVoice': 'ভয়েস ইনপুট শুরু করুন',
    'input.stopRecording': 'রেকর্ডিং বন্ধ করুন',
    'input.stopRecognition': 'শোনা বন্ধ করুন',
    'card.heading.description': 'বর্ণনা',
    'card.placeholder.noDescription': 'কোনো বর্ণনা উপলব্ধ নেই',
    'card.heading.summary': 'তথ্য সারাংশ',
    'card.placeholder.noSummary': 'কোনো সারাংশ উপলব্ধ নেই',
    'card.heading.educational': 'শিক্ষামূলক অন্তর্দৃষ্টি: প্রভাবিত করার কৌশল ও সুরক্ষা',
    'card.heading.sources': 'উৎস, বিশ্বাসযোগ্যতা স্কোর ও সিদ্ধান্ত',
    'card.heading.educationalSection': 'শিক্ষামূলক অন্তর্দৃষ্টি',
    'card.heading.misleadingIndicators': 'ভ্রান্তিকর সূচক:',
    'card.heading.deepfakeDetection': 'ডিপফেক শনাক্তকরণ:',
    'card.badge.detected': 'সনাক্ত',
    'card.badge.notDetected': 'সনাক্ত নয়',
    'card.text.confidencePercent': '{{value}}% নির্ভরযোগ্যতা',
    'card.label.overallVerdict': 'চূড়ান্ত সিদ্ধান্ত:',
    'card.trust.sourceIntegrity': 'উৎসের অখণ্ডতা',
    'card.trust.contentAuthenticity': 'বিষয়বস্তুর সত্যতা',
    'card.trust.trustExplainability': 'বিশ্বাসের ব্যাখ্যাযোগ্যতা',
    'card.heading.sourceInformation': 'উৎস তথ্য',
    'card.label.domain': 'ডোমেইন:',
    'card.label.author': 'লেখক:',
    'card.label.published': 'প্রকাশিত:',
    'card.label.reputation': 'খ্যাতি:',
    'card.label.status': 'অবস্থা:',
    'card.label.ssl': 'SSL:',
    'card.text.sslEnabled': 'সক্রিয়',
    'card.text.sslDisabled': 'নিষ্ক্রিয়',
    'card.heading.sourcesButton': 'উৎস',
    'card.dialog.title': 'উৎস ও যাচাইকরণ বিস্তারিত',
    'card.dialog.description': 'উৎস তথ্য ও যাচাইকরণ ফলাফল',
    'card.dialog.referenced': 'উল্লিখিত উৎস ({{count}})',
    'card.dialog.noSources': 'এই বিশ্লেষণের জন্য কোনো উৎস উপলব্ধ নেই',
    'card.text.deepfakeConfidence': 'নির্ভরযোগ্যতা:',
    'card.details.technical': 'প্রযুক্তিগত বিবরণ',
    'card.banner.deepfakeDetected': 'ডিপফেক সনাক্ত',
    'card.banner.deepfakeNotDetected': 'ডিপফেক সনাক্ত হয়নি',
    'dynamic.error.analysisFailed': 'বিশ্লেষণ সম্পূর্ণ করা যায়নি।'
  },
  'ta-IN': {
    'input.placeholder.default': 'உரை, URL என்பவற்றை பகுப்பாய்வு செய்யவும் அல்லது படம், வீடியோ, ஆடியோ கோப்புகளை ஒட்டு/விடவும்...',
    'input.placeholder.recording': 'ஒலி பதிவு செய்யப்படுகிறது...',
    'input.placeholder.listening': 'கேட்டுக்கொண்டிருக்கிறது...',
    'input.placeholder.file': 'உங்கள் கேள்வி அல்லது பகுப்பாய்வு கோரிக்கையை சேர்க்கவும்',
    'input.placeholder.ready': 'உங்கள் உள்ளடக்கத்தை பகுப்பாய்வு செய்ய தயாராக உள்ளது',
    'input.dropHere': 'உங்கள் கோப்பை இங்கே விடவும்',
    'input.attachFile': 'கோப்பை இணைக்கவும்',
    'input.startVoice': 'குரல் உள்ளீட்டை தொடங்கவும்',
    'input.stopRecording': 'பதிவை நிறுத்தவும்',
    'input.stopRecognition': 'கேட்பதை நிறுத்தவும்',
    'card.heading.description': 'விளக்கம்',
    'card.placeholder.noDescription': 'விளக்கம் இல்லை',
    'card.heading.summary': 'தகவல் சுருக்கம்',
    'card.placeholder.noSummary': 'சுருக்கம் இல்லை',
    'card.heading.educational': 'கல்வி அறிவுரை: மோசடி முறைகள் மற்றும் பாதுகாப்பு வழிகள்',
    'card.heading.sources': 'மூலங்கள், நம்பிக்கை மதிப்பெண்கள் மற்றும் தீர்ப்பு',
    'card.heading.educationalSection': 'கல்வி அறிவுரைகள்',
    'card.heading.misleadingIndicators': 'தவறாக வழிநடத்தும் சுட்டீடுகள்:',
    'card.heading.deepfakeDetection': 'டீப் ஃபேக் கண்டறிதல்:',
    'card.badge.detected': 'கண்டறியப்பட்டது',
    'card.badge.notDetected': 'கண்டறியப்படவில்லை',
    'card.text.confidencePercent': '{{value}}% நம்பிக்கை',
    'card.label.overallVerdict': 'இறுதி தீர்ப்பு:',
    'card.trust.sourceIntegrity': 'மூலங்களின் நேர்மை',
    'card.trust.contentAuthenticity': 'உள்ளடக்க உண்மை தன்மை',
    'card.trust.trustExplainability': 'நம்பிக்கை விளக்கம்',
    'card.heading.sourceInformation': 'மூல தகவல்',
    'card.label.domain': 'டொமைன்:',
    'card.label.author': 'ஆசிரியர்:',
    'card.label.published': 'வெளியீடு:',
    'card.label.reputation': 'புகழ்:',
    'card.label.status': 'நிலை:',
    'card.label.ssl': 'SSL:',
    'card.text.sslEnabled': 'இயக்கப்பட்டுள்ளது',
    'card.text.sslDisabled': 'முடக்கப்பட்டுள்ளது',
    'card.heading.sourcesButton': 'மூலங்கள்',
    'card.dialog.title': 'மூலங்கள் மற்றும் சரிபார்ப்பு விவரங்கள்',
    'card.dialog.description': 'மூல தகவல் மற்றும் சரிபார்ப்பு முடிவுகள்',
    'card.dialog.referenced': 'குறிப்பிடப்பட்ட மூலங்கள் ({{count}})',
    'card.dialog.noSources': 'இந்த பகுப்பாய்வுக்கு மூலங்கள் கிடைக்கவில்லை',
    'card.text.deepfakeConfidence': 'நம்பிக்கை:',
    'card.details.technical': 'தொழில்நுட்ப விவரங்கள்',
    'card.banner.deepfakeDetected': 'டீப் ஃபேக் கண்டறியப்பட்டது',
    'card.banner.deepfakeNotDetected': 'டீப் ஃபேக் இல்லை',
    'dynamic.error.analysisFailed': 'பகுப்பாய்வை முடிக்க முடியவில்லை.'
  },
  'te-IN': {
    'input.placeholder.default': 'పాఠ్యాన్ని, URL ను విశ్లేషించండి లేదా చిత్రం, వీడియో, ఆడియో ఫైల్‌ను పేస్ట్/డ్రాప్ చేయండి...',
    'input.placeholder.recording': 'ఆడియో రికార్డ్ అవుతోంది...',
    'input.placeholder.listening': 'వింటోంది...',
    'input.placeholder.file': 'మీ ప్రశ్న లేదా విశ్లేషణ అభ్యర్థనను జోడించండి',
    'input.placeholder.ready': 'మీ కంటెంట్‌ను విశ్లేషించడానికి సిద్ధంగా ఉంది',
    'input.dropHere': 'మీ ఫైలును ఇక్కడ విడిచేయండి',
    'input.attachFile': 'ఫైలును జోడించండి',
    'input.startVoice': 'వాయిస్ ఇన్‌పుట్ ప్రారంభించండి',
    'input.stopRecording': 'రికార్డింగ్ నిలిపివేయండి',
    'input.stopRecognition': 'వినడం ఆపు',
    'card.heading.description': 'వివరణ',
    'card.placeholder.noDescription': 'వివరణ అందుబాటులో లేదు',
    'card.heading.summary': 'సమాచార సారాంశం',
    'card.placeholder.noSummary': 'సారాంశం అందుబాటులో లేదు',
    'card.heading.educational': 'విద్యా అవగాహన: మోసపూరిత పద్ధతులు మరియు రక్షణ చర్యలు',
    'card.heading.sources': 'మూలాలు, విశ్వసనీయ స్కోర్లు మరియు తీర్పు',
    'card.heading.educationalSection': 'విద్యా అవగాహనలు',
    'card.heading.misleadingIndicators': 'మార్గం తప్పించే సూచికలు:',
    'card.heading.deepfakeDetection': 'డీప్‌ఫేక్ గుర్తింపు:',
    'card.badge.detected': 'గుర్తించబడింది',
    'card.badge.notDetected': 'గుర్తించబడలేదు',
    'card.text.confidencePercent': '{{value}}% నమ్మకం',
    'card.label.overallVerdict': 'చివరి తీర్పు:',
    'card.trust.sourceIntegrity': 'మూల సమగ్రత',
    'card.trust.contentAuthenticity': 'కంటెంట్ నిజత్వం',
    'card.trust.trustExplainability': 'నమ్మక వివరణ',
    'card.heading.sourceInformation': 'మూల సమాచారం',
    'card.label.domain': 'డొమైన్:',
    'card.label.author': 'రచయిత:',
    'card.label.published': 'ప్రచురించినది:',
    'card.label.reputation': 'ప్రతిష్ఠ:',
    'card.label.status': 'స్థితి:',
    'card.label.ssl': 'SSL:',
    'card.text.sslEnabled': 'ప్రారంభించబడింది',
    'card.text.sslDisabled': 'నిలిపివేయబడింది',
    'card.heading.sourcesButton': 'మూలాలు',
    'card.dialog.title': 'మూలాలు మరియు ధృవీకరణ వివరాలు',
    'card.dialog.description': 'మూల సమాచారం మరియు ధృవీకరణ ఫలితాలు',
    'card.dialog.referenced': 'సూచించిన మూలాలు ({{count}})',
    'card.dialog.noSources': 'ఈ విశ్లేషణకు మూలాలు లేవు',
    'card.text.deepfakeConfidence': 'నమ్మకం:',
    'card.details.technical': 'సాంకేతిక వివరాలు',
    'card.banner.deepfakeDetected': 'డీప్‌ఫేక్ గుర్తించబడింది',
    'card.banner.deepfakeNotDetected': 'డీప్‌ఫేక్ గుర్తించబడలేదు',
    'dynamic.error.analysisFailed': 'విశ్లేషణ పూర్తిచేయలేకపోయాం.'
  },
  'mr-IN': {
    'input.placeholder.default': 'मजकूर, URL विश्लेषित करा किंवा प्रतिमा, व्हिडिओ, ऑडिओ फाइल पेस्ट/ड्रॉप करा...',
    'input.placeholder.recording': 'ऑडिओ रेकॉर्ड होत आहे...',
    'input.placeholder.listening': 'ऐकत आहे...',
    'input.placeholder.file': 'आपला प्रश्न किंवा विश्लेषण विनंती जोडा',
    'input.placeholder.ready': 'आपली सामग्री विश्लेषित करण्यास तयार',
    'input.dropHere': 'आपली फाइल येथे टाका',
    'input.attachFile': 'फाइल जोडा',
    'input.startVoice': 'वॉइस इनपुट सुरू करा',
    'input.stopRecording': 'रेकॉर्डिंग थांबवा',
    'input.stopRecognition': 'ऐकणे थांबवा',
    'card.heading.description': 'वर्णन',
    'card.placeholder.noDescription': 'वर्णन उपलब्ध नाही',
    'card.heading.summary': 'माहिती सारांश',
    'card.placeholder.noSummary': 'सारांश उपलब्ध नाही',
    'card.heading.educational': 'शैक्षणिक माहिती: दिशाभूल करणाऱ्या तंत्र आणि संरक्षण उपाय',
    'card.heading.sources': 'स्रोत, विश्वास स्कोअर आणि निर्णय',
    'card.heading.educationalSection': 'शैक्षणिक माहिती',
    'card.heading.misleadingIndicators': 'गैरमार्गदर्शक दर्शक:',
    'card.heading.deepfakeDetection': 'डीपफेक तपासणी:',
    'card.badge.detected': 'आढळले',
    'card.badge.notDetected': 'आढळले नाही',
    'card.text.confidencePercent': '{{value}}% विश्वास',
    'card.label.overallVerdict': 'अंतिम निर्णय:',
    'card.trust.sourceIntegrity': 'स्रोत प्रामाणिकता',
    'card.trust.contentAuthenticity': 'सामग्रीची सत्यता',
    'card.trust.trustExplainability': 'विश्वास स्पष्टता',
    'card.heading.sourceInformation': 'स्रोत माहिती',
    'card.label.domain': 'डोमेन:',
    'card.label.author': 'लेखक:',
    'card.label.published': 'प्रकाशित:',
    'card.label.reputation': 'प्रतिष्ठा:',
    'card.label.status': 'स्थिती:',
    'card.label.ssl': 'SSL:',
    'card.text.sslEnabled': 'सक्रिय',
    'card.text.sslDisabled': 'निष्क्रिय',
    'card.heading.sourcesButton': 'स्रोत',
    'card.dialog.title': 'स्रोत व सत्यापन तपशील',
    'card.dialog.description': 'स्रोत माहिती आणि सत्यापन निकाल',
    'card.dialog.referenced': 'संदर्भित स्रोत ({{count}})',
    'card.dialog.noSources': 'या विश्लेषणासाठी कोणतेही स्रोत उपलब्ध नाहीत',
    'card.text.deepfakeConfidence': 'विश्वास:',
    'card.details.technical': 'तांत्रिक तपशील',
    'card.banner.deepfakeDetected': 'डीपफेक आढळले',
    'card.banner.deepfakeNotDetected': 'डीपफेक आढळले नाही',
    'dynamic.error.analysisFailed': 'विश्लेषण पूर्ण करता आले नाही.'
  },
  'gu-IN': {
    'input.placeholder.default': 'પાઠ્ય, URLનું વિશ્લેષણ કરો અથવા છબી, વિડિયો, ઑડિયો ફાઈલ પેસ્ટ/ડ્રોપ કરો...',
    'input.placeholder.recording': 'ઑડિયો રેકોર્ડ થઈ રહ્યું છે...',
    'input.placeholder.listening': 'સાંભળવામાં આવે છે...',
    'input.placeholder.file': 'તમારો પ્રશ્ન અથવા વિશ્લેષણ વિનંતી ઉમેરો',
    'input.placeholder.ready': 'તમારી સામગ્રીનું વિશ્લેષણ કરવા તૈયાર',
    'input.dropHere': 'તમારી ફાઈલ અહીં મૂકો',
    'input.attachFile': 'ફાઈલ જોડો',
    'input.startVoice': 'વૉઇસ ઇનપુટ શરૂ કરો',
    'input.stopRecording': 'રેકોર્ડિંગ બંધ કરો',
    'input.stopRecognition': 'સાંભળવું બંધ કરો',
    'card.heading.description': 'વર્ણન',
    'card.placeholder.noDescription': 'કોઈ વર્ણન ઉપલબ્ધ નથી',
    'card.heading.summary': 'માહિતી સારાંશ',
    'card.placeholder.noSummary': 'કોઈ સારાંશ ઉપલબ્ધ નથી',
    'card.heading.educational': 'શૈક્ષણિક અવલોકન: ગેરમાર્ગે દોરવાની પદ્ધતિઓ અને સુરક્ષા પગલાં',
    'card.heading.sources': 'સ્ત્રોતો, વિશ્વસનીયતા સ્કોર અને નિર્ણય',
    'card.heading.educationalSection': 'શૈક્ષણિક અવલોકનો',
    'card.heading.misleadingIndicators': 'ગેરમાર્ગે દોરનારા સૂચકો:',
    'card.heading.deepfakeDetection': 'ડીપફેક શોધ:',
    'card.badge.detected': 'હણાયો',
    'card.badge.notDetected': 'હણાયો નથી',
    'card.text.confidencePercent': '{{value}}% વિશ્વાસ',
    'card.label.overallVerdict': 'અંતિમ નિર્ણય:',
    'card.trust.sourceIntegrity': 'સ્ત્રોતની અખંડિતતા',
    'card.trust.contentAuthenticity': 'સામગ્રીની વાસ્તવિકતા',
    'card.trust.trustExplainability': 'વિશ્વાસની સ્પષ્ટતા',
    'card.heading.sourceInformation': 'સ્ત્રોત માહિતી',
    'card.label.domain': 'ડોમેન:',
    'card.label.author': 'લેખક:',
    'card.label.published': 'પ્રકાશિત:',
    'card.label.reputation': 'ખ્યાતિ:',
    'card.label.status': 'સ્થિતિ:',
    'card.label.ssl': 'SSL:',
    'card.text.sslEnabled': 'સક્રિય',
    'card.text.sslDisabled': 'નિષ્ક્રિય',
    'card.heading.sourcesButton': 'સ્ત્રોતો',
    'card.dialog.title': 'સ્ત્રોત અને ચકાસણી વિગતો',
    'card.dialog.description': 'સ્ત્રોત માહિતી અને ચકાસણી પરિણામો',
    'card.dialog.referenced': 'સંદર્ભિત સ્ત્રોતો ({{count}})',
    'card.dialog.noSources': 'આ વિશ્લેષણ માટે કોઈ સ્ત્રોત ઉપલબ્ધ નથી',
    'card.text.deepfakeConfidence': 'વિશ્વાસ:',
    'card.details.technical': 'તકનિકી વિગતો',
    'card.banner.deepfakeDetected': 'ડીપફેક મળી આવ્યું',
    'card.banner.deepfakeNotDetected': 'ડીપફેક નથી મળ્યું',
    'dynamic.error.analysisFailed': 'વિશ્લેષણ પૂર્ણ કરી શકાયું નથી.'
  },
  'kn-IN': {
    'input.placeholder.default': 'ಪಠ್ಯ, URL ವಿಶ್ಲೇಷಿಸಿ ಅಥವಾ ಚಿತ್ರ, ವೀಡಿಯೋ, ಆಡಿಯೋ ಫೈಲ್ ಅನ್ನು ಅಂಟಿಸಿ/ಬಿಡಿ...',
    'input.placeholder.recording': 'ಆಡಿಯೊ ದಾಖಲಾಗುತ್ತಿದೆ...',
    'input.placeholder.listening': 'ಕೆಳುತ್ತಿದೆ...',
    'input.placeholder.file': 'ನಿಮ್ಮ ಪ್ರಶ್ನೆ ಅಥವಾ ವಿಶ್ಲೇಷಣೆಯ ವಿನಂತಿಯನ್ನು ಸೇರಿಸಿ',
    'input.placeholder.ready': 'ನಿಮ್ಮ ವಿಷಯವನ್ನು ವಿಶ್ಲೇಷಿಸಲು ಸಿದ್ಧವಾಗಿದೆ',
    'input.dropHere': 'ನಿಮ್ಮ ಫೈಲ್ ಅನ್ನು ಇಲ್ಲಿ ಬಾಡಿ',
    'input.attachFile': 'ಫೈಲ್ ಅನ್ನು ಜೋಡಿಸಿ',
    'input.startVoice': 'ಧ್ವನಿ ಇನ್‌ಪುಟ್ ಪ್ರಾರಂಭಿಸಿ',
    'input.stopRecording': 'ದಾಖಲಿಸುವಿಕೆಯನ್ನು ನಿಲ್ಲಿಸಿ',
    'input.stopRecognition': 'ಕೆಳುವುದನ್ನು ನಿಲ್ಲಿಸಿ',
    'card.heading.description': 'ವಿವರಣೆ',
    'card.placeholder.noDescription': 'ವಿವರಣೆ ಲಭ್ಯವಿಲ್ಲ',
    'card.heading.summary': 'ಮಾಹಿತಿ ಸಾರಾಂಶ',
    'card.placeholder.noSummary': 'ಸಾರಾಂಶ ಲಭ್ಯವಿಲ್ಲ',
    'card.heading.educational': 'ಶೈಕ್ಷಣಿಕ ಒಳನೋಟ: ಮರುಳು ಮಾಡುವ ವಿಧಾನಗಳು ಮತ್ತು ರಕ್ಷಣಾ ಕ್ರಮಗಳು',
    'card.heading.sources': 'ಮೂಲಗಳು, ವಿಶ್ವಾಸ ಸ್ಕೋರ್ ಮತ್ತು ತೀರ್ಪು',
    'card.heading.educationalSection': 'ಶೈಕ್ಷಣಿಕ ಒಳನೋಟಗಳು',
    'card.heading.misleadingIndicators': 'ತಪ್ಪು ದಾರಿ ಸೂಚಕಗಳು:',
    'card.heading.deepfakeDetection': 'ಡೀಪ್‌ಫೇಕ್ ಪತ್ತೆ:',
    'card.badge.detected': 'ಕಂಡುಹಿಡಿಯಲಾಗಿದೆ',
    'card.badge.notDetected': 'ಕಂಡುಹಿಡಿಯಲಾಗಿಲ್ಲ',
    'card.text.confidencePercent': '{{value}}% ವಿಶ್ವಾಸ',
    'card.label.overallVerdict': 'ಅಂತಿಮ ತೀರ್ಪು:',
    'card.trust.sourceIntegrity': 'ಮೂಲ ಸಮಗ್ರತೆ',
    'card.trust.contentAuthenticity': 'ವಿಷಯದ ಪ್ರಾಮಾಣಿಕತೆ',
    'card.trust.trustExplainability': 'ವಿಶ್ವಾಸ ಸ್ಪಷ್ಟತೆ',
    'card.heading.sourceInformation': 'ಮೂಲ ಮಾಹಿತಿ',
    'card.label.domain': 'ಡೊಮೈನ್:',
    'card.label.author': 'ಲೇಖಕ:',
    'card.label.published': 'ಪ್ರಕಟಿಸಿದ:',
    'card.label.reputation': 'ಖ್ಯಾತಿ:',
    'card.label.status': 'ಸ್ಥಿತಿ:',
    'card.label.ssl': 'SSL:',
    'card.text.sslEnabled': 'ಸಕ್ರಿಯ',
    'card.text.sslDisabled': 'ನಿಷ್ಕ್ರಿಯ',
    'card.heading.sourcesButton': 'ಮೂಲಗಳು',
    'card.dialog.title': 'ಮೂಲಗಳು ಮತ್ತು ಪರಿಶೀಲನೆ ವಿವರಗಳು',
    'card.dialog.description': 'ಮೂಲ ಮಾಹಿತಿ ಮತ್ತು ಪರಿಶೀಲನೆ ಫಲಿತಾಂಶಗಳು',
    'card.dialog.referenced': 'ಉಲ್ಲೇಖಿತ ಮೂಲಗಳು ({{count}})',
    'card.dialog.noSources': 'ಈ ವಿಶ್ಲೇಷಣೆಗೆ ಮೂಲಗಳು ಲಭ್ಯವಿಲ್ಲ',
    'card.text.deepfakeConfidence': 'ವಿಶ್ವಾಸ:',
    'card.details.technical': 'ತಾಂತ್ರಿಕ ವಿವರಗಳು',
    'card.banner.deepfakeDetected': 'ಡೀಪ್‌ಫೇಕ್ ಕಂಡುಬಂದಿದೆ',
    'card.banner.deepfakeNotDetected': 'ಡೀಪ್‌ಫೇಕ್ ಕಾಣಿಸಲಿಲ್ಲ',
    'dynamic.error.analysisFailed': 'ವಿಶ್ಲೇಷಣೆಯನ್ನು ಪೂರ್ಣಗೊಳಿಸಲಾಗಲಿಲ್ಲ.'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState(DEFAULT_LANGUAGE);

  const translate = useCallback(
    (key: string, replacements?: TranslationReplacements) => {
      const dictionary = TRANSLATIONS[language] || TRANSLATIONS[DEFAULT_LANGUAGE];
      const fallbackDictionary = TRANSLATIONS[DEFAULT_LANGUAGE];
      const template = dictionary?.[key] ?? fallbackDictionary?.[key] ?? key;
      if (!replacements) {
        return template;
      }
      return Object.entries(replacements).reduce((acc, [target, value]) => {
        return acc.replace(new RegExp(`{{${target}}}`, 'g'), String(value));
      }, template);
    },
    [language]
  );

  return (
    <LanguageContext.Provider value={{ language, setLanguage, translate }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
